services:
  db:
    image: mysql:8.0
    container_name: fms_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fms
      MYSQL_USER: fms
      MYSQL_PASSWORD: fms
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: fms_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db

  mailhog:
    image: mailhog/mailhog
    container_name: fms_mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  db_data:
